### ISSUE TITLE
运行您的项目出错，良久未解决，请您帮助

### ISSUE THREAD

**Issue by Liu9527i** [gwybwqs/movies#5]
### **您好，我在尝试运行您的项目时发生了报错，尝试网上很多种方法依旧没有解决，希望您能给一些帮助，谢谢！**

1.特意下的webstorm，版本是2019.1，用webstorm 导入movies-web项目时右下角弹窗里执行了 npm install 后出现以下内容
```
"E:\Program Files\nodejs\node.exe" "E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install --scripts-prepend-node-path=auto

> chromedriver@2.46.0 install C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1)

ChromeDriver is already available at 'C:\Users\18508\AppData\Local\Temp\2.46\chromedriver\chromedriver.exe'.
Copying to target path C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\chromedriver\lib\chromedriver
Done. ChromeDriver binary available at C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\chromedriver\lib\chromedriver\chromedriver.exe

> core-js@2.6.11 postinstall C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack\node_modules\uglifyjs-webpack-plu
gin
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32
","arch":"x64"})

added 1756 packages from 1109 contributors and audited 1832 packages in 58.047s

24 packages are looking for funding
  run `npm fund` for details

found 777 vulnerabilities (711 low, 33 moderate, 32 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Process finished with exit code 0

```

**2.然后在Terminal  执行 npm run dev 发生了如下 的报错**

```
`Microsoft Windows [版本 10.0.19042.928]
(c) Microsoft Corporation。保留所有权利。

C:\Users\18508\Desktop\movies\movies\movies-web>npm run dev

> movies-web@1.0.0 dev C:\Users\18508\Desktop\movies\movies\movies-web
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\18508\Desktop\movies\movies\movies-web\build\webpack.dev.conf.js'
Require stack:
- C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack\bin\convert-argv.js
- C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requireConfig (C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (C:\Users\18508\Desktop\movies\movies\movies-web\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\18508\\Desktop\\movies\\movies\\movies-web\\node_modules\\webpack\\bin\\convert-argv.js',
    'C:\\Users\\18508\\Desktop\\movies\\movies\\movies-web\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! movies-web@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the movies-web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\node\npm-cache\_logs\2021-04-28T10_14_26_171Z-debug.log

C:\Users\18508\Desktop\movies\movies\movies-web>
`
```

**Comment by yandong667** [comment]
能否交流下？sj4498606
